### PR TITLE
reordered and reorganized questions that define plaintiff defendant r…

### PR DESCRIPTION
**Pull request by CaroRob**
…elationship

### CODE REVIEW

**Review by plocket — CHANGES_REQUESTED** [review]
Once we remove a reference to one variable, I think this will be merge-able. I'll change it tonight and push, but let's test that version before we pull it in.

Variable:
209a_package.yml, line 85, reference to `relationship_to_defendant_unmarried` needs to be removed.

**Comment by plocket** [comment]
Thank you for the PR!

**Comment by CaroRob** [comment]
Made a mistake about that variable 

> > Variable:
> 209a_package.yml, line 85, reference to relationship_to_defendant_unmarried needs to be removed

Actually I think it needs to be replaced. We were using it in the 209A package yml to get to a certain point in the Page 1 yml, we were then going to divert to page 2 before returning back to Page 1. We were using that relationship_to_defendant_unmarried as a marker, I think the variable to replace it with should be 
**plaintiff_has_minor_children**
We finish asking about plaintiff's relationship with defendant. The next question is about the number of children under 18 plaintiff has and that should then send us to 209A Page 2 questions, before returning back to the rest of the questions on 209A Page 1.

**Comment by CaroRob** [comment]
Folllowed up with defendant plaintiff relationship part2 so closing this pull request

**Pull request closed without merging**
