### PR TITLE
Progress on addendum integration.

### PR DESCRIPTION
**Pull request by nonprofittechy**
Known issue: aff. of care or custody is not done

### CODE REVIEW

**Review by plocket — CHANGES_REQUESTED** [review]
Running into errors around questions about cases with children. Will give more detailed report in a bit.

**Comment by plocket** [comment]
I tested without any extra cases and there was no error, though a few issues need to be filed. For the errors I found, see #305 and #306.

**Comment by plocket** [comment]
After signing the doc, I got more questions about addresses (and I think previous address) in a weird order (the first child, the second child, the 'another person' that was involved somewhere along the way, the 8th child) and then I ran into an error: `'children[7].previous_addresses.put_on_appendix' that could not be looked up`

The full error:
[pr-addenda-2_30-error.txt](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4691389/pr-addenda-2_30-error.txt)

The JSON:
[pr-addenda-2_30-vars.txt](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4691386/pr-addenda-2_30-vars.txt)

Other than that, the red error `flash`es came up for cases after listing attorneys for multiple children (it worked fine for one). Pic of one such occasion below:

Screen Shot 2020-05-27 at 7 40 46 AM

**Comment by nonprofittechy** [comment]
you just merged the commit that changes address order.

The appendix error comes from the addendum code that Lily added; I'll see if I can track it down. that other kind of error flash is usually from validation code, but I don't remember any on that particular screen. I'll take a closer look.

**Comment by nonprofittechy** [comment]
I'm now thinking the red flash is due to a list collect bug fixed upstream. just upgraded server versions-we were each testing on different servers.

**Comment by plocket** [comment]
The attorney flash (validation) errors are gone. There are other issues that may have been fixed by the latest commits. We are going to assume for now that this commit did not bring up issues that didn't already exist.

**Pull request merged**
