### PR TITLE
Reorganize address question

### PR DESCRIPTION
**Pull request by nonprofittechy**

### CODE REVIEW

**Comment by nonprofittechy** [comment]
Move address questions explicitly to the end. More natural question style; allow skipping when all children live at the same address. Test with 1 and 2 children, same/different addresses

**Comment by plocket** [comment]
[IMPORTANT EDIT: This was using the test.yml. I don't know why it'd call that error because that's such a straightforward test that isn't defining anything and is asking for only the necessary info, but it's still important to know.]

I got a non-terminating error. Not bug, but user error notification that looked like a validation error: `Error: 'children[i].previous_addresses[0]'` Tell me if you want the JSON.

I also need to write one of these for the other PR. I'll try to remember to do that.

```
question: |
  Previous Addresses for ${children[i]}
subquestion: |
  List each address other than ${children[i].address.on_one_line(include_unit=True)}
  where ${children[i]} has lived in the last 2 years below.

  To add more than one, click ${word("Add another")}.
list collect:
  enable: True
  label: |
    ${ordinal(j).capitalize()} Address
fields:
  - An address previously mentioned: children[i].previous_addresses[j]
    datatype: object
    choices: collected_addresses
    disable others: True
    object labeler: |
      lambda y: y.on_one_line(include_unit=True)
    exclude: children[i].address
  - Address: children[i].previous_addresses[j].address
    address autocomplete: True
  - Unit:     children[i].previous_addresses[j].unit
    required: False
  - City: children[i].previous_addresses[j].city
  - State: children[i].previous_addresses[j].state
    code: |
      states_list()
    default: "MA"
How question came to be asked
Tried to run mandatory code at 0.00000s
mandatory: True
code: |
  evaluate_child_addresses # 
Needed definition of evaluate_child_addresses at 0.00003s
Tried to ask question at 0.00010s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

scan for variables: False
sets: evaluate_child_addresses
code: |
  if children_address_screener == 'me':
    for child in children_of_both:
      child.address = users[0].address
  elif children_address_screener == 'defendant':
    for child in children_of_both:
      child.address = other_parties[0].address
  else:
    for child in children_of_both:
      child.address.address
  if len(children_of_both) > 1 and children_address_screener == 'me' or children_address_screener == 'defendant':
    if children_lived_elsewhere:
      for child in children_of_both:
        child.previous_addresses.there_are_any
        child.previous_addresses.minimum_number = 1
        child.previous_addresses.gather()
    else:
      for child in children_of_both:
        child.previous_addresses.there_are_any = False
  else:
    for child in children_of_both: # will be only one child
      child.previous_addresses.gather()

  evaluate_child_addresses = True
Needed definition of children_of_both at 0.00016s
Tried to ask question at 0.00022s
(from 209A_complaint_for_protection_from_abuse_probation.yml)

id: custom_objects
objects:
  - children: PeopleList.using(ask_number=True)
  - children_cares_for: PeopleList.using(ask_number=True)
  - children_of_both: PeopleList.using(auto_gather=False)
  - wants_custody_of: PeopleList
  - wants_no_contact_for: PeopleList
  - schools_to_stay_away_from: DAList.using(object_type=Person)
  - majors_needing_support: PeopleList
Tried to ask question at 0.00040s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

scan for variables: False
sets: evaluate_child_addresses
code: |
  if children_address_screener == 'me':
    for child in children_of_both:
      child.address = users[0].address
  elif children_address_screener == 'defendant':
    for child in children_of_both:
      child.address = other_parties[0].address
  else:
    for child in children_of_both:
      child.address.address
  if len(children_of_both) > 1 and children_address_screener == 'me' or children_address_screener == 'defendant':
    if children_lived_elsewhere:
      for child in children_of_both:
        child.previous_addresses.there_are_any
        child.previous_addresses.minimum_number = 1
        child.previous_addresses.gather()
    else:
      for child in children_of_both:
        child.previous_addresses.there_are_any = False
  else:
    for child in children_of_both: # will be only one child
      child.previous_addresses.gather()

  evaluate_child_addresses = True
Needed definition of children_of_both.gathered at 0.00046s
Tried to ask question at 0.00054s
(from 209A_complaint_for_protection_from_abuse_probation.yml)

reconsider: True
code: |
  children_of_both = children.filter(defendant_is_parent = True)
  children_of_both.gathered = True
  build_children_of_both_list  = True
Tried to ask question at 0.00066s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

scan for variables: False
sets: evaluate_child_addresses
code: |
  if children_address_screener == 'me':
    for child in children_of_both:
      child.address = users[0].address
  elif children_address_screener == 'defendant':
    for child in children_of_both:
      child.address = other_parties[0].address
  else:
    for child in children_of_both:
      child.address.address
  if len(children_of_both) > 1 and children_address_screener == 'me' or children_address_screener == 'defendant':
    if children_lived_elsewhere:
      for child in children_of_both:
        child.previous_addresses.there_are_any
        child.previous_addresses.minimum_number = 1
        child.previous_addresses.gather()
    else:
      for child in children_of_both:
        child.previous_addresses.there_are_any = False
  else:
    for child in children_of_both: # will be only one child
      child.previous_addresses.gather()

  evaluate_child_addresses = True
Needed definition of children[0].previous_addresses[0].address at 0.00075s
Needed definition of escape_button at 0.00214s
Tried to ask question at 0.00219s
(from escape.yml)

id: escape_button_and_its_placement
template: escape_button
content: |
  <script>

    // Can't use `let` in here
    var escaper = escaper || document.createElement( 'a' );
    escaper.setAttribute( 'class', 'escape btn btn-danger' );
    escaper.setAttribute( 'href', 'https://google.com' );
    escaper.innerHTML = 'Escape';

    // Add to navbar
    var after = document.getElementById( 'damobile-toggler' );
    after.parentNode.insertBefore( escaper, after );

  </script>

  <style>
    
    .escape {
      margin: 0;
      margin-left: .4em;
    }
    
    @media only screen and (max-width: 30em) {
      .navbar-brand {
        margin-right: .3rem;
      }
      
      #dapagetitle {
        margin-right: .4em;
      }
      
      #dapagetitle .ma_icon {
        margin-right: 0;
      }

      .escape {
        margin-left: .6em;
      }
      
      #dahelptoggle {
        padding: 0;
      }
    }
  </style>
Needed definition of collected_addresses at 0.00428s
Tried to ask question at 0.00433s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

reconsider: True
code: |
  collected_addresses = list(set([child.address for child in children_of_both.elements if defined('child.address.address')] + [user.address for user in users] + [other_party.address for other_party in other_parties if other_party.address.on_one_line(include_unit=True) != users[0].address.on_one_line(include_unit=True)] + collected_previous_addressess))
Needed definition of collected_previous_addressess at 0.07236s
Tried to ask question at 0.07243s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

reconsider: True
code: |
  temp_previous_addresses = []
  if defined('children_address_screener'):
    for child in children_of_both:
      for address in child.previous_addresses.complete_elements():
        temp_previous_addresses.append(address)
  collected_previous_addressess = temp_previous_addresses
Tried to ask question at 0.08491s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

reconsider: True
code: |
  collected_addresses = list(set([child.address for child in children_of_both.elements if defined('child.address.address')] + [user.address for user in users] + [other_party.address for other_party in other_parties if other_party.address.on_one_line(include_unit=True) != users[0].address.on_one_line(include_unit=True)] + collected_previous_addressess))
Completed processing at 0.16550s
Tried to run mandatory code at 0.18087s
mandatory: True
code: |
  evaluate_child_addresses # 
Needed definition of evaluate_child_addresses at 0.18091s
Tried to ask question at 0.18097s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

scan for variables: False
sets: evaluate_child_addresses
code: |
  if children_address_screener == 'me':
    for child in children_of_both:
      child.address = users[0].address
  elif children_address_screener == 'defendant':
    for child in children_of_both:
      child.address = other_parties[0].address
  else:
    for child in children_of_both:
      child.address.address
  if len(children_of_both) > 1 and children_address_screener == 'me' or children_address_screener == 'defendant':
    if children_lived_elsewhere:
      for child in children_of_both:
        child.previous_addresses.there_are_any
        child.previous_addresses.minimum_number = 1
        child.previous_addresses.gather()
    else:
      for child in children_of_both:
        child.previous_addresses.there_are_any = False
  else:
    for child in children_of_both: # will be only one child
      child.previous_addresses.gather()

  evaluate_child_addresses = True
Needed definition of children_of_both at 0.18103s
Tried to ask question at 0.18109s
(from 209A_complaint_for_protection_from_abuse_probation.yml)

id: custom_objects
objects:
  - children: PeopleList.using(ask_number=True)
  - children_cares_for: PeopleList.using(ask_number=True)
  - children_of_both: PeopleList.using(auto_gather=False)
  - wants_custody_of: PeopleList
  - wants_no_contact_for: PeopleList
  - schools_to_stay_away_from: DAList.using(object_type=Person)
  - majors_needing_support: PeopleList
Tried to ask question at 0.18126s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

scan for variables: False
sets: evaluate_child_addresses
code: |
  if children_address_screener == 'me':
    for child in children_of_both:
      child.address = users[0].address
  elif children_address_screener == 'defendant':
    for child in children_of_both:
      child.address = other_parties[0].address
  else:
    for child in children_of_both:
      child.address.address
  if len(children_of_both) > 1 and children_address_screener == 'me' or children_address_screener == 'defendant':
    if children_lived_elsewhere:
      for child in children_of_both:
        child.previous_addresses.there_are_any
        child.previous_addresses.minimum_number = 1
        child.previous_addresses.gather()
    else:
      for child in children_of_both:
        child.previous_addresses.there_are_any = False
  else:
    for child in children_of_both: # will be only one child
      child.previous_addresses.gather()

  evaluate_child_addresses = True
Needed definition of children_of_both.gathered at 0.18131s
Tried to ask question at 0.18139s
(from 209A_complaint_for_protection_from_abuse_probation.yml)

reconsider: True
code: |
  children_of_both = children.filter(defendant_is_parent = True)
  children_of_both.gathered = True
  build_children_of_both_list  = True
Tried to ask question at 0.18150s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

scan for variables: False
sets: evaluate_child_addresses
code: |
  if children_address_screener == 'me':
    for child in children_of_both:
      child.address = users[0].address
  elif children_address_screener == 'defendant':
    for child in children_of_both:
      child.address = other_parties[0].address
  else:
    for child in children_of_both:
      child.address.address
  if len(children_of_both) > 1 and children_address_screener == 'me' or children_address_screener == 'defendant':
    if children_lived_elsewhere:
      for child in children_of_both:
        child.previous_addresses.there_are_any
        child.previous_addresses.minimum_number = 1
        child.previous_addresses.gather()
    else:
      for child in children_of_both:
        child.previous_addresses.there_are_any = False
  else:
    for child in children_of_both: # will be only one child
      child.previous_addresses.gather()

  evaluate_child_addresses = True
Needed definition of children[0].previous_addresses[0].address at 0.18160s
Needed definition of collected_addresses at 0.18408s
Tried to ask question at 0.18413s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

reconsider: True
code: |
  collected_addresses = list(set([child.address for child in children_of_both.elements if defined('child.address.address')] + [user.address for user in users] + [other_party.address for other_party in other_parties if other_party.address.on_one_line(include_unit=True) != users[0].address.on_one_line(include_unit=True)] + collected_previous_addressess))
Needed definition of collected_previous_addressess at 0.24015s
Tried to ask question at 0.24022s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

reconsider: True
code: |
  temp_previous_addresses = []
  if defined('children_address_screener'):
    for child in children_of_both:
      for address in child.previous_addresses.complete_elements():
        temp_previous_addresses.append(address)
  collected_previous_addressess = temp_previous_addresses
Tried to ask question at 0.25507s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)

reconsider: True
code: |
  collected_addresses = list(set([child.address for child in children_of_both.elements if defined('child.address.address')] + [user.address for user in users] + [other_party.address for other_party in other_parties if other_party.address.on_one_line(include_unit=True) != users[0].address.on_one_line(include_unit=True)] + collected_previous_addressess))
Completed processing at 0.34519s
```

**Comment by plocket** [comment]
Tried to proceed to the next page again, and got it, this time for indexes 0, 1, and 2 (I have three addresses). The first address answer (which was a previous address - the user's address) gets erased and it stays on the same page.

**Comment by plocket** [comment]
After putting in a non-previous address, the app moves on to the next page with another two error flashes, this time naming indexes 1 and 2.

**Comment by nonprofittechy** [comment]
This appears to be the same problem that was fixed in the other commit with reconsidering `children_of_both`. I recommend we merge and then try to reproduce--in another branch if you want. but testing this without the other fix isn't going to be useful.

**Pull request merged**
