### PR TITLE
Add PDF answer key, switch to numbers for children, etc.

### PR DESCRIPTION
**Pull request by plocket**
You can [test it out here](https://apps-dev.suffolklitlab.org/interview?new_session=1&i=docassemble.playground12fillerDev%3A209a-filler.yml#page1)

### CODE REVIEW

**Comment by plocket** [comment]
You can [test it out here](https://apps-dev.suffolklitlab.org/interview?new_session=1&i=docassemble.playground12fillerDev%3A209a-filler.yml#page1)

**Comment by plocket** [comment]
I think it'd be fairly quick to adjust it so the user can choose for it to be a skipper.

**Comment by nonprofittechy** [comment]
You don't need me to review when you're adding a completely independent file. But i did want to point out that the user/OP names are shifted off by one row. First name goes into the middle name field, e.g.,

**Comment by plocket** [comment]
I'm not sure what you mean as I wasn't able to replicate what I think you're describing, @nonprofittechy , but I suspect you don't have time to drop a screenshot. I'll keep an eye out for it and thank you for stopping by!

**Comment by nonprofittechy** [comment]
image
image

This is using the test link you provided: https://apps-dev.suffolklitlab.org/interview?new_session=1&i=docassemble.playground12fillerDev%3A209a-filler.yml#page1

Edit: now I see this is a known limit of your design. I assumed you were using JS to pre-fill defaults. But it's a bit confusing to use right now.

**Comment by plocket** [comment]
Thank you for the screenshots, @nonprofittechy. Didn't catch your notes at the end. It is a bit confusing, but I haven't found a good way to explain it and we'll be working with people individually anyway, so I hope they'll get the hang of it. ~That is exactly how the page is meant to appear. If the user's first name is defined, the question will be skipped and that is not the intended use of this tool. All other fields are meant to be filled.~

**Comment by nonprofittechy** [comment]
Maybe if you took out the middle names, it would be clearer that it's working how it's supposed to. Right now it looks like the middle name is meant to go in the first-name field.

**Comment by plocket** [comment]
I hear what you're saying and appreciate the brainstorming. This isn't the only place that confuses people, though. People find a lot of spots confusing with this tool. Because of that, I'm currently defaulting to filling in as many fields as possible instead while hoping to address confusion in-person. I'll keep an eye out to see if this seems to be the major blocker though and, if it is, change tactics around how this is handled.

**Comment by plocket** [comment]
Got the go ahead from one of the requested reviewers on Slack. These comments are good to keep thinking about moving forward.

**Pull request merged**
