### PR TITLE
New download screen

### PR DESCRIPTION
**Pull request by nonprofittechy**
Also disables review screens; remove new lines from list of people allowed to view confidential info page

### CODE REVIEW

**Review by CaroRob — CHANGES_REQUESTED** [review]
Oh dear I spent a while trying to answer every question just to test other stuff along the way - many github issues :( but when I got to screen after preview:
Error
Retry
[Error after testing  New download screen #484 2020-07-08](https://docs.google.com/document/d/1VtefcI5NTwx6SCR25iSmpLdiI-ZQF0-hjIJbkPpaVjo/edit?usp=sharing)

Interview has an error. There was a reference to a variable 'download_screen' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.

**Comment by nonprofittechy** [comment]
Sorry about that! I'm glad you tested it. Added the missing event just now

**Comment by CaroRob** [comment]
Oh crikey - getting too late to work - sorry just ran through the whole thing again quickly got the same error then realized I forgot to download your changes.

**Comment by CaroRob** [comment]
Ok me again - 
Download had to do a ton of other stuff before I could get back to you on this.
I thought I could commit to a new branch to your branch and ask for a PR, instead i ended up sending a commit with new language to your branch - sorry.
The screen still needs a way to allow plaintiff to email to themself.
Is there anyway we could make the directions download or email to yourself links to allow them to do so? Just asking. If not easy we at least need to put in that email to someone/yourself at the bottom?

**Comment by nonprofittechy** [comment]
The built-in email  link doesn't work with a form that has addenda :-(

I think I have a simple stop gap solution--the share button from MADE, which takes you to a new screen to send the email. Michelle has something she has used with the CORI project, but I think it would take more time to drop that in and adapt it to our style and needs as well as validate it.

**Comment by nonprofittechy** [comment]
I'm going to merge this for now, but open an issue to add the share via email button somehow. Also asking Jonathan on Slack for more ideas.

**Pull request merged**
