### PR TITLE
Remove some extraneous code

### PR DESCRIPTION
**Pull request by plocket**
This is for puppeteer code that's no longer needed. These are things like going to the interview or logging into the playground when those actions aren't relevant anymore. I think they were initially done to figure stuff out.

### CODE REVIEW

**Comment by plocket** [comment]
Re-thinking a bit - maybe `install-branch.js` really should run the interview to make sure that it loads after installation? It doesn't quite match up with the test that makes sure that the interview runs at all. Is there another way we can test that the repo branch was successfully installed?

**Comment by plocket** [comment]
Also, it looks like we might still have a race condition problem. We might need to increase the default timeout.

**Comment by plocket** [comment]
~Nope, I've introduced an error somehow. ~
> ~This is the TEST_URL:https://apps-dev.suffolklitlab.org//interview?reset=1&i=docassemble.playground***testingunusedcode%3A209a_package.yml~

No, that's just the secret not being shown. Hmm. It runs locally.

It failed after running for two seconds. Maybe PR #586 will help with this. We might also convert it to a cucumber test next.

**Comment by plocket** [comment]
Or remove `test` altogether. Or, alternatively, take `test` out of actions, but keep it as a script that runs `setup`, `cucumber`, and `takedown` so I don't have to keep typing those in.

**Comment by plocket** [comment]
Gotta love those screenshots. The ID secret got changed. Wonder if there's a log of who changed it.

**Comment by plocket** [comment]
If you look at the old screenshots, it wasn't a timeout error. The Playground thought the interview didn't exist. When I tried to use the account something was wrong with it. The code is as it was when I originally pushed it, but now it's working, so... yeah.

**Comment by niharikasingh** [comment]
> Re-thinking a bit - maybe `install-branch.js` really should run the interview to make sure that it loads after installation? It doesn't quite match up with the test that makes sure that the interview runs at all. Is there another way we can test that the repo branch was successfully installed?

Yup - this is my only concern with this PR. If we remove the `waitForPage` function, I don't think we check anywhere that the interview is running.

**Comment by plocket** [comment]
There is a cucumber test specifically for that. I do think there might be a different test we could do - make sure that the branch pulled in was the correct branch. There's something weird happening with that at the moment. Hit me up on Slack to discuss more. It's a bit complex to describe.

**Comment by plocket** [comment]
☝️ @niharikasingh

**Comment by plocket** [comment]
I've figured out what that code is for and it's very specific and different than the other code. What it's actually testing is when the server has really restarted. That means that when the cucumber tests run, they're working with a server that's ready. This PR should definitely be changed or closed. I'm leaning towards closed.

That said, I have concerns about some other stuff I'm seeing with issues pulling in the correct branch. I have to check out some more things.

**Pull request closed without merging**
