### PR TITLE
Don't ask about visitation if there are no `children_of_both`. fix #459

### LINKED ISSUE #459: 209A Plaintiff with children without defendant as father gets asked about visitation
Court can only make visitation orders about children of both parties. If none of the under 18 plaintiff's own children have defendant as father, then plaintiff should not get asked question about visitation.

### PR DESCRIPTION
**Pull request by nonprofittechy**

### CODE REVIEW

**Review by CaroRob — CHANGES_REQUESTED** [review]
Got asked visitation almost at the very end  - just after Where will you file? Error stuff copied into Google Doc [Visitation Screen still getting asked PR 459 2020-07-09](https://docs.google.com/document/d/1REiqanljpXkSRvmSCy4arlWz04Jx3Ee7sCJlR15fkgI/edit?usp=sharing)

**Comment by nonprofittechy** [comment]
@CaroRob I think this PR is ready now. I found the offending trigger--when you asked for no other page 2 relief, correct?

**Comment by CaroRob** [comment]
Yes, I think so. I was racing through, so we asked for no page 2 relief. Gonna try it now.

**Comment by CaroRob** [comment]
Ok it worked with no other relief for children requested we did not get asked about visitation - perfect. Merging now.

**Pull request merged**
