### PR TITLE
Make use of the new BirthDate selector

### PR DESCRIPTION
**Pull request by nonprofittechy**

### CODE REVIEW

**Review by CaroRob — COMMENTED** [review]
I would take the date label off the field
the month box is not big/wide enough to hold the whole word for a month like September
the day/date box is not a drop down - just open - I don't know if that is intentional or browser specific, or... it doesn't follow the pattern of most date entry fields across the Internet - and is a little disconcerting when the months are a dropdown
Page id: non_parent_children, v1.0.13 - is not using this selector

We can certainly merge if you want - not exactly sure what you want to do next.

**Comment by nonprofittechy** [comment]
We did a lot of research to find good models of date inputs, and this is what we landed on. 

Goals: it is easier for people to type a date than to choose from a dropdown if it is a date they have memorized. But 3 free-text entry fields lead to errors--people will not know which field is for the month, for example. Dropdown month helps with correct use.

See the Gmail signup date selector as an example of this style:

image

I think we can keep tweaking it--good points on labels and width of inputs. But currently the calendar selector leads to many errors, and one person reporting they couldn't use the form at all. See: https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/issues/683

But I'd like to get this in the upcoming release. I think even if it's not perfect, it's a big improvement for usability.

**Comment by nonprofittechy** [comment]
> id: non_parent_children

I'll fix this before merge.

Re removing Date label--we can do alternate text, but the field needs a label to look correct. The spacing is very odd without a label.

**Review by CaroRob — COMMENTED** [review]
Yep - good to go for now. I meant to pick approve radio button but missed and only submitted with comment - can't figure out how to approve now. and not merging cause of "some checks haven't completed yet.' But as far as I am concerned we are good to go on merging this when those puppeteer checks finish.

**Comment by nonprofittechy** [comment]
Tests appear invalid

**Pull request merged**
